# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "bun"
    open-pull-requests-limit: 50
    commit-message:
      prefix: "Bun - "
    directory: "/src"
    schedule:
      interval: "monthly"
    labels:
      - ":label: Dependencies"
      - ":technologist:TypeScript/JavaScript :green_circle:"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Github Actions - "
    directory: ./.github/workflows/
    schedule:
      interval: "monthly"
    labels:
      - ":label: Dependencies"
      - ":technologist: Github Actions :brown_circle:"
  - package-ecosystem: "gitsubmodule"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "Submodule - "
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - ":label: Dependencies"
      - ":technologist: Submodules :large_blue_circle:"