name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'dist'
    
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: "Build Resume PDF"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Build PDF
        id: build
        run: make build-docker
      - name: Upload PDF artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: './dist/resume.pdf'
      - name: Commit PDF to Repository
        if: github.ref == 'refs/heads/main' && github.repository == 'dylanlangston/resume'
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git add dist/resume.pdf
          git commit -m "PDF Update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"
          git push origin main